//! All steps for creating an authentication system using express + Ejs + mongoose
//TODO:-- create package.json
//  npm init -y
//TODO:-- install all required dependencies
// npm i express  cookie-parser bcrypt jsonwebtoken ejs
//TODO:-- create a basic server
//Importing the express and using this call get() and send son=me response to the port
//TODO:-- require(because we use coomonjs) all necessary packages
// cookieParser, path
//? I have use 'ejs' to render HTML pages  and send the variable value
// LIKE:-- app.set("view engine","ejs")
//         res.render("HTML file name",{name:"barun"})
//? static() indicates to the express to serve static files.
//? express.static(path.join(__dirname, 'public'))--> serve static files from public folder.
//! From now Authentication and Authorization is started
//TODO:-- Create two folder: views( contains all html pages) and public(contains all static pages)
//? Inside public folder create another 3 folders name: images,stylesheets,javascript
//? Inside  views folder create index.ejs file 
//! what i have to do next
//? (a) create user account
//? (b) set up mongoes
//? (c) create schema
//? (d) create model
//? (e) usercreate -> password -> hash
//? (f) jwt token -> cookie
//? (g) login-> token -> decrypt--> email
//TODO:- install mongoose
//? create a folder models.And inside the model create a file user.js
//? Inside user.js create connection with mongoDB by connecting string and create userSchema and then export it
//? use this schema inside app.js(main file)
// ? create a form for get the user data inside index.ejs 
//? destructure user submitted information from req.body 
//? create salt(random string) by bcrypt for the security purpose of the password
//? now create hash of that salt(string).
//TODO:-- Now with the help of bcrypt we can create salt and hash the password 
//? After hashing the password it will be assigened to user's password
//? Now finally hashed password and user rremaining data are to be stored inside database
//TODO:-- use jwt to send the token to the browser so that next time,when user request something to server then
//TODO:-- No need for asking login details to the user within the cookie session.But internally Browser give the token to the server for authentication purpose. 
//? Now store the user data intyo dataBase by create().
//? jwt.sign({email},"secretKey")--> with these two 'email' and 'secretKey' jwt create a token and send it to the browser.
//TODO:-- logout
//? when user want to log out then browser will replace the existing cookie with ""(empty string value) and redirect the user to the home page.
//TODO:--Login
//? when user is in login page,after he fill up and submit the form, data will receive into req.body.
//? By destructuring req.body server can get all individual data and on the basis of password and email 
//? it will decide user is valid or not.
//? By th help of findOne() we can get whole stored data of the user.
//? now stored email and user given email will be compared by bcrypt.compare() -> returns value true or false.
//?  if matched then send the token (generated by jwt.sign) to the browser.
//? 
